### ISSUE TITLE
vulnerability to PROJ6/GDAL3

### ISSUE THREAD

**Issue by rsbivand** [riatelab/tanaka#1]
Running revdeps from sp (sp (my github fork) with development rgdal from R-Forge):

```
> packageVersion("sp")
[1] ‘1.3.4’
> packageVersion("rgdal")
[1] ‘1.5.3’
> rgdal::rgdal_extSoftVersion()
          GDAL GDAL_with_GEOS           PROJ             sp 
       "3.0.2"         "TRUE"        "6.2.1"        "1.3-2" 
```
a test fails:

```
> test_check("tanaka")
── 1. Failure: contour works (@test_tanaka.R#12)  ──────────────────────────────
`tanaka_contour(x = ras, mask = as(com, "Spatial"))` produced warnings.

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 8 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 1 ]
1. Failure: contour works (@test_tanaka.R#12) 

Error: testthat unit tests failed
Execution halted
```

See:

http://rgdal.r-forge.r-project.org/articles/PROJ6_GDAL3.html
https://github.com/r-spatial/sf/issues/1231
https://github.com/r-spatial/sf/issues/1187
https://github.com/r-spatial/sf/issues/1146
https://github.com/r-spatial/discuss/issues/28

for background. See:

https://github.com/r-spatial/discuss/issues/28#issuecomment-551241421

for a way of testing fixes in a docker container contributed by Jakub Nowosad.

**Comment by rCarto** [comment]
Thanks, I'll check asap!

**Comment by rCarto** [comment]
commit 37be8f3155e740ddecf73d5e643aa22062bf80e6 should have fixed the problem.

**Comment by edzer** [comment]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

upcoming sf still breaks tanaka on CRAN; let me know if you need help to sort this out.

**Comment by rCarto** [comment]
Thanks, I'll adapt tanaka to the sf release and submit to CRAN on monday. 
Moreover, thank you (and contributors) for your work on sf.

**Comment by rCarto** [comment]
The problem was the use of different proj representation in `raster` and `sf`. The solution involve the use of `st_crs(x)$proj4string`. 
New submission to CRAN should work with sf<=0.9 and PROJ >=5
