### ISSUE TITLE
Control of image size?

### ISSUE THREAD

**Issue by beroe** [riatelab/tanaka#5]
This package is great and produces really nice results.

I can't figure out how to control the native size of the image that is generated..?

**Comment by rCarto** [comment]
I'm not sure that I understand your question. The produced image is a classic R plot. Its size depends on the settings of  the graphic device it is plotted on.

``` r
library(tanaka)
library(terra)
#> terra 1.7.3
ras <- rast(system.file("tif/elev.tif", package = "tanaka"))

png("export1.png", width = 1000, height = 1000)
tanaka(ras, breaks = seq(80,400,20), 
       legend.pos = "topright", 
       legend.title = "Elevation\n(meters)")
dev.off()
#> png 
#>   2

png("export2.png", width = 400, height = 400)
tanaka(ras, breaks = seq(80,400,20), 
       legend.pos = "topright", 
       legend.title = "Elevation\n(meters)")
dev.off()
#> png 
#>   2
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup> 
export1.png:

![export1.png](https://user-images.githubusercontent.com/3041254/222099855-bab1b955-0b96-4f21-8ea5-bfa6474d351d.png)

export2.png:

![export2.png](https://user-images.githubusercontent.com/3041254/222099902-d715252c-d28f-4f4d-aeae-3709975e2757.png)



It is also possible to use export features of  `mapsf`:

``` r
library(mapsf)
library(tanaka)
library(terra)
#> terra 1.7.3
ras <- rast(system.file("tif/elev.tif", package = "tanaka"))
mf_theme(mar = c(.5,.5,.5,.5))
mf_export(x = ras, filename = "export3.png", width = 800, expandBB = c(0,0,0,.15))
tanaka(ras, breaks = seq(80,400,20), 
       legend.pos = "topright", 
       legend.title = "Elevation\n(meters)", 
       add = TRUE)
dev.off()
#> png 
#>   2
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup> 
export3.png:

![export3](https://user-images.githubusercontent.com/3041254/222103838-a2f573ae-3d44-401f-aaba-22792350d6cf.png)

**Comment by beroe** [comment]
Thanks very much. These look great. I just wasn't sure whether the plots generated were pixel-based, and thus looked odd when scaled up upon saving. It sounds like that is not the case.

**Comment by rCarto** [comment]
Yes it is a vector image.

**Comment by beroe** [comment]
That is amazing. Thanks.
